### ISSUE TITLE
deal.II master floating point exception

### ISSUE THREAD

**Issue by tjhei** [geodynamics/aspect#4960]
This currently happens:
```
solver_scheme_no_advection_single_stokes ...........................***Failed    1.48 sec
*** "Test solver_scheme_no_advection_single_stokes failed": ***
[1/1] Generating output-solver_scheme_no_advection_single_stokes/screen-output
FAILED: output-solver_scheme_no_advection_single_stokes/screen-output 
cd /__w/aspect/aspect/build/tests && /__w/aspect/aspect/tests/cmake/timeout.sh 600s /__w/aspect/aspect/tests/cmake/run_test.sh 0 /__w/aspect/aspect/build/aspect /__w/aspect/aspect/build/tests/solver_scheme_no_advection_single_stokes.x.prm /__w/aspect/aspect/build/tests/output-solver_scheme_no_advection_single_stokes/screen-output.tmp && /__w/aspect/aspect/tests/cmake/default screen-output </__w/aspect/aspect/build/tests/output-solver_scheme_no_advection_single_stokes/screen-output.tmp >/__w/aspect/aspect/build/tests/output-solver_scheme_no_advection_single_stokes/screen-output
/__w/aspect/aspect/tests/cmake/run_test.sh: line 16: 29001 Floating point exception(core dumped) $BINARY $PRM > ${OUTPUT} 2>&1
-----------------------------------------------------------------------------
-- This is ASPECT, the Advanced Solver for Problems in Earth's ConvecTion.
--     . version 2.5.0-pre
--     . using deal.II 9.5.0-pre (master, 3e88b26172)
--     .       with 32 bit indices and vectorization level 1 (128 bits)
--     . using Trilinos 12.14.1
--     . using p4est 2.2.0
--     . running in DEBUG mode
--     . running with 1 MPI process
-----------------------------------------------------------------------------

Loading shared library <./libsolver_scheme_no_advection_single_stokes.so>

Vectorization over 2 doubles = 128 bits (SSE2), VECTORIZATION_LEVEL=1
-----------------------------------------------------------------------------
-- For information on how to cite ASPECT, see:
--   https://aspect.geodynamics.org/citing.html?ver=2.5.0-pre&mf=1&sha=&src=code
-----------------------------------------------------------------------------
Number of active cells: 256 (on 5 levels)
Number of degrees of freedom: 3,556 (2,178+289+1,089)

*** Timestep 0:  t=0 seconds, dt=0 seconds
   Solving Stokes system... 0+
```

see here for example: https://github.com/geodynamics/aspect/actions/runs/3090660726/jobs/4999751630#step:6:1627

**Comment by tjhei** [comment]
git bisect blames the following PR [#14270](https://github.com/dealii/dealii/pull/14270/), which is somewhat confusing.

**Comment by tjhei** [comment]
backtrace:
```
#1  0x00007fffd1a437f1 in __GI_abort () at abort.c:79
#2  0x00007fffeaa85508 in dealii::deal_II_exceptions::internals::abort (exc=...) at ../source/base/exceptions.cc:500
#3  0x00007fffe2d48c26 in dealii::deal_II_exceptions::internals::issue_error_noreturn<dealii::StandardExceptions::ExcNumberNotFinite> (handling=dealii::deal_II_exceptions::internals::ExceptionHandling::abort_or_throw_on_exception, 
    file=0x7ffff2df2668 "../include/deal.II/lac/la_parallel_vector.templates.h", line=1853, 
    function=0x7ffff2df9e40 <dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::norm_sqr_local() const::__PRETTY_FUNCTION__> "dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::real_type dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::norm_sqr_local() const [with Number = double; MemorySpace = "..., cond=0x7ffff2df39c0 "dealii::numbers::is_finite(sum)", 
    exc_name=0x7ffff2df3988 "dealii::ExcNumberNotFinite(std::complex<double>(sum))", e=...) at ../include/deal.II/base/exceptions.h:1403
#4  0x00007fffe9dbfcb3 in dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::norm_sqr_local (this=0x55555ac77140) at ../include/deal.II/lac/la_parallel_vector.templates.h:1853
#5  0x00007fffe9dbdb19 in dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::norm_sqr (this=0x55555ac77140) at ../include/deal.II/lac/la_parallel_vector.templates.h:1931
#6  0x00007fffe9dbdadc in dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::l2_norm (this=0x55555ac77140) at ../include/deal.II/lac/la_parallel_vector.templates.h:1945
#7  0x0000555557d018f7 in aspect::internal::BlockSchurGMGPreconditioner<aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::ABlockOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::MassMatrixOperator<2, 1, double>, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> >, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> > >::vmult (this=0x7fffffff72f0, dst=..., src=...) at /home/heister/aspect-git2/source/simulator/stokes_matrix_free.cc:628
#8  0x0000555557d064a4 in dealii::SolverFGMRES<dealii::LinearAlgebra::distributed::BlockVector<double> >::solve<aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double>, aspect::internal::BlockSchurGMGPreconditioner<aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::ABlockOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::MassMatrixOperator<2, 1, double>, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> >, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> > > > (this=0x7fffffff7ac0, A=..., x=..., b=..., preconditioner=...) at /home/heister/deal-git2/include/deal.II/lac/solver_gmres.h:1317
#9  0x0000555557bf1f82 in aspect::StokesMatrixFreeHandlerImplementation<2, 2>::solve (this=0x55555a865260) at /home/heister/aspect-git2/source/simulator/stokes_matrix_free.cc:2538
#10 0x0000555557bdedba in aspect::Simulator<2>::solve_stokes (this=0x7fffffff9ef0) at /home/heister/aspect-git2/source/simulator/solver.cc:528
#11 0x0000555557be5aee in aspect::Simulator<2>::assemble_and_solve_stokes (this=0x7fffffff9ef0, compute_initial_residual=false, initial_nonlinear_residual=0x0) at /home/heister/aspect-git2/source/simulator/solver_schemes.cc:400
#12 0x0000555557be62ad in aspect::Simulator<2>::solve_no_advection_single_stokes (this=0x7fffffff9ef0) at /home/heister/aspect-git2/source/simulator/solver_schemes.cc:1050
#13 0x000055555797e7fb in aspect::Simulator<2>::solve_timestep (this=0x7fffffff9ef0) at /home/heister/aspect-git2/source/simulator/core.cc:1836
#14 0x000055555797b785 in aspect::Simulator<2>::run (this=0x7fffffff9ef0) at /home/heister/aspect-git2/source/simulator/core.cc:2009
#15 0x000055555922c39e in run_simulator<2> (
    raw_input_as_string="# solcx test, based on no_cheap_gmg.prm to show \"no Advection, single Stokes\"\n# scheme works\n\nset Dimension = 2\n\n\nset CFL number", ' ' <repeats 29 times>, "= 1.0\n\nset End time", ' ' <repeats 24 times>..., input_as_string="# solcx test, based on no_cheap_gmg.prm to show \"no Advection, single Stokes\"\n# scheme works\n\nset Dimension = 2\n\n\nset CFL number", ' ' <repeats 29 times>, "= 1.0\n\nset End time", ' ' <repeats 24 times>..., 
    output_xml=false, output_plugin_graph=false, validate_only=false) at /home/heister/aspect-git2/source/main.cc:598
#16 0x00005555591e623e in main (argc=2, argv=0x7fffffffdd98) at /home/heister/aspect-git2/source/main.cc:785
```
